#!/usr/bin/env python3
"""Bundle the extension: copy model artifacts + generate entity list + fetch ORT.

  python apps/extension/build.py

Steps:
  1. assets/model.int8.onnx + assets/vocab.txt  <- models/artifacts/student/
  2. assets/political_entities.js               <- labeling/lexicons/political_entities.txt
     (single source of truth: the same file the Python side uses)
  3. lib/ort/                                   <- onnxruntime-web dist via npm

Then load apps/extension/ as an unpacked extension (chrome://extensions,
Developer mode, "Load unpacked").
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

EXT = Path(__file__).resolve().parent
REPO = EXT.parents[1]
STUDENT = REPO / "models" / "artifacts" / "student"
ENTITIES = REPO / "src" / "manipulens" / "labeling" / "lexicons" / "political_entities.txt"
ORT_VERSION = "1.20.1"


def copy_model() -> None:
    assets = EXT / "assets"
    assets.mkdir(exist_ok=True)
    src = STUDENT / "model.int8.onnx"
    if not src.exists():
        sys.exit(f"missing {src} — run `make distill export-onnx` first")
    shutil.copy2(src, assets / "model.int8.onnx")
    print(f"assets/model.int8.onnx  ({src.stat().st_size / 1e6:.1f} MB)")

    # vocab.txt: copy directly, or extract from the fast tokenizer.json
    vocab_txt = STUDENT / "vocab.txt"
    out = assets / "vocab.txt"
    if vocab_txt.exists():
        shutil.copy2(vocab_txt, out)
    else:
        tok = json.loads((STUDENT / "tokenizer.json").read_text())
        vocab: dict[str, int] = tok["model"]["vocab"]
        ordered = sorted(vocab.items(), key=lambda kv: kv[1])
        out.write_text("\n".join(t for t, _ in ordered) + "\n")
    print(f"assets/vocab.txt  ({out.stat().st_size / 1e6:.1f} MB)")


def gen_entities() -> None:
    terms = [
        ln.strip().lower()
        for ln in ENTITIES.read_text().splitlines()
        if ln.strip() and not ln.startswith("#")
    ]
    out = EXT / "assets" / "political_entities.js"
    out.write_text(
        "/* GENERATED by build.py from labeling/lexicons/political_entities.txt"
        " — do not edit */\n"
        f"globalThis.MANIPULENS_POLITICAL_ENTITIES = {json.dumps(terms)};\n"
    )
    print(f"assets/political_entities.js  ({len(terms)} terms)")


def fetch_ort() -> None:
    ort_dir = EXT / "lib" / "ort"
    if (ort_dir / "ort.min.js").exists():
        print("lib/ort/ already present, skipping npm fetch")
        return
    ort_dir.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        subprocess.run(
            ["npm", "install", "--no-save", "--prefix", tmp, f"onnxruntime-web@{ORT_VERSION}"],
            check=True,
            capture_output=True,
        )
        dist = Path(tmp) / "node_modules" / "onnxruntime-web" / "dist"
        for f in dist.iterdir():
            if f.suffix in (".wasm", ".mjs") or f.name == "ort.min.js":
                shutil.copy2(f, ort_dir / f.name)
                print(f"lib/ort/{f.name}  ({f.stat().st_size / 1e6:.1f} MB)")


if __name__ == "__main__":
    copy_model()
    gen_entities()
    fetch_ort()
    print("\nready: load apps/extension/ as an unpacked extension")
